# Generated by Django 3.0.3 on 2020-04-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20200424_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='song_name',
            new_name='song_title',
        ),
    ]
